[package]
name = "gui"
version = "0.9.9"
edition = "2019"
default-run = "ntsc-rs-standalone"
license = "GPL-3.0"
repository = "https://github.com/valadaptive/ntsc-rs/tree/main/crates/gui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntscrs = { path = "../ntscrs" }
arboard = "3.3.2"
eframe = { version = "0.27", features=["persistence"] }
env_logger = "0.10.0"
image = "0.24.7"
snafu = "0.7.5"
logos = "0.13"
gstreamer = "0.21"
gstreamer-base = "0.21"
gstreamer-video = "0.21"
gstreamer-controller = "0.21"
futures-lite = "2.2.0"
async-executor = "1.5.1"
async-task = "4.7.0"
waker-fn = "1.1.0"
log = "0.4.20"
rfd = { git = "https://github.com/valadaptive/rfd", rev = "fe3d331" }
rand = "0.8.5"
tinyjson = "2.5.1"

[build-dependencies]
embed-resource = "2.4"

[[bin]]
name = "ntsc-rs-standalone"

[[bin]]
name = "ntsc-rs-launcher"
