[package]
name = "ae-plugin"
version = "0.1.0"
edition = "2021"
license = "MIT OR ISC OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[target.'cfg(any(windows, target_os="macos"))'.dependencies]
after-effects = {git = "https://github.com/AdrianEddy/after-effects", rev = "e2650d1"}
ntscrs = { path = "../ntscrs" }

[target.'cfg(any(windows, target_os="macos"))'.build-dependencies]
pipl = {git = "https://github.com/AdrianEddy/after-effects", rev = "e2650d1"}
